### ISSUE TITLE
repo 이름과 형식을 빌려가도 될까요?

### ISSUE THREAD

**Issue by dozzzang** [devetude/interview-question-algorithm#1]
안녕하세요.
편입학 자료구조 면접을 앞두고 있습니다. 우연히 선생님의 repo를 보게 되었는데 저도 선생님처럼 정리해보고 싶어 issue 남깁니다.
저작권을 남기고 형식과 repo 이름을 빌리고 내용은 다르게 하여 repo를 만들어도 될까요?

**Comment by devetude** [comment]
@dozzzang 너무 늦게 확인했네요, 오픈소스이니 물론 가능합니다!
